# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:01_products.sql,classpath:02_product_variants.sql,classpath:03_product_variant_images.sql
spring.jpa.defer-datasource-initialization=true

# JWT
app.jwt-secret=${JWT_SECRET}
app.jwt-expiration=604800000

# Google OAuth
app.google-client-id=${GOOGLE_CLIENT_ID:your-google-client-id}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:8080/api/payment/vnpay/return}
vnpay.ipn-url=${VNPAY_IPN_URL:}
vnpay.version=2.1.0
vnpay.command=pay
vnpay.currency-code=VND
vnpay.locale=vn

# Frontend URL
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# Thu muc luu file upload
app.upload-dir=uploads

# URL goc cua backend
app.base-url=http://localhost:8080

# Gioi han kich thuoc file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# Gemini AI
gemini.api.key=${GEMINI_API_KEY:}

# Groq AI
groq.api.key=${GROQ_API_KEY:}